---
include:
  - board: eyelash_corne_left
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: >-
      -DCONFIG_ZMK_STUDIO=y
      -DCONFIG_ZMK_STUDIO_LOCKING=n
  - board: eyelash_corne_right
    shield: nice_view
  # - board: eyelash_corne_left
  #   shield: nice_view
  #   snippet: zmk-usb-logging
  - board: eyelash_corne_left
    shield: settings_reset
