draw_config:
  dark_mode: auto
  n_columns: 1
  combo_diagrams_scale: 3

parse_config:
  sticky_label: 👆
  trans_legend:
    tap: ⁛
    type: trans

  raw_binding_map:
    '&sys_reset': Reset
    '&bootloader': Boot
    '&studio_unlock': 🔓
    '&caps_word': Caps Word
    '&inv_qm': ¿

    '&out OUT_USB': Out USB
    '&out OUT_BLE': Out BLE

    '&bt BT_SEL 0': BT 1
    '&bt BT_SEL 1': BT 2
    '&bt BT_SEL 2': BT 3
    '&bt BT_SEL 3': BT 4
    '&bt BT_SEL 4': BT 5

    '&mmv MOVE_UP': Mouse ↑
    '&mmv MOVE_DOWN': Mouse ↓
    '&mmv MOVE_LEFT': Mouse ←
    '&mmv MOVE_RIGHT': Mouse →

    '&msc SCRL_UP': Scroll ↑
    '&msc SCRL_DOWN': Scroll ↓
    '&msc SCRL_LEFT': Scroll ←
    '&msc SCRL_RIGHT': Scroll →

    '&mkp LCLK': Left Click
    '&mkp RCLK': Right Click
    '&mkp MCLK': Middle Click
    '&mkp MB4': Back Click
    '&mkp MB5': Forward Click

    "&kp LS(LC(LA(N1)))": 1️⃣
    "&kp LS(LC(LA(N2)))": 2️⃣
    "&kp LS(LC(LA(N3)))": 3️⃣
    "&kp LS(LC(LA(N4)))": 4️⃣
    "&kp LS(LC(LA(N5)))": 5️⃣
    "&kp LS(LC(LA(N6)))": 6️⃣
    "&kp LS(LC(LA(N7)))": 7️⃣
    "&kp LS(LC(LA(N8)))": 8️⃣
    "&kp LS(LC(LA(N9)))": 9️⃣
    "&kp LS(LC(LA(N0)))": 0️⃣

    "&layer_en_qwerty": EN QWERTY
    "&layer_en_colemak": EN Colemak
    "&layer_ru_jcuken": RU JCUKEN

  zmk_keycode_map:
    C_PP: ⏯
    C_STOP: ⏹
    C_NEXT: ⏭️
    C_PREV: ⏮️
    C_VOL_UP: 🔊+
    C_VOL_DN: 🔊-
    C_MUTE: 🔇

    LCTRL: Ctrl
    RCTRL: Ctrl
    LALT: Alt
    RALT: AltGr
    LGUI: Gui
    RGUI: Gui
    LSHFT: Shift
    RSHFT: Shift
    ESC: Esc
    SPACE: ␣
    BSPC: ⌫
    RET: ⏎
    TAB: ↹
    DEL: ⌦

    PG_UP: Page ↑
    PG_DN: Page ↓
    INS: Insert
    HOME: Home
    END: End
    CAPS: Caps Lock
    SLCK: Scroll Lock
    PSCRN: Print Scrn
    PAUSE_BREAK: Pause Break

    UP: ↑
    DOWN: ↓
    LEFT: ←
    RIGHT: →

    C_PP: ⏯
    C_NEXT: ⏭️
    C_PREV: ⏮️

    # defaults
    AMPERSAND: '&'
    AMPS: '&'
    APOS: "'"
    APOSTROPHE: "'"
    ASTERISK: '*'
    ASTRK: '*'
    AT: '@'
    AT_SIGN: '@'
    BACKSLASH: \
    BSLH: \
    CARET: ^
    COLON: ':'
    COMMA: ','
    DLLR: $
    DOLLAR: $
    DOT: .
    DOUBLE_QUOTES: '"'
    DQT: '"'
    EQUAL: '='
    EXCL: '!'
    EXCLAMATION: '!'
    FSLH: /
    GRAVE: '`'
    GREATER_THAN: '>'
    GT: '>'
    HASH: '#'
    LBKT: '['
    LBRC: '{'
    LEFT_BRACE: '{'
    LEFT_BRACKET: '['
    LEFT_PARENTHESIS: (
    LESS_THAN: <
    LPAR: (
    LT: <
    MINUS: '-'
    NON_US_BACKSLASH: \
    NON_US_BSLH: '|'
    NON_US_HASH: '#'
    NUHS: '#'
    PERCENT: '%'
    PERIOD: .
    PIPE: '|'
    PIPE2: '|'
    PLUS: +
    POUND: '#'
    PRCNT: '%'
    QMARK: '?'
    QUESTION: '?'
    RBKT: ']'
    RBRC: '}'
    RIGHT_BRACE: '}'
    RIGHT_BRACKET: ']'
    RIGHT_PARENTHESIS: )
    RPAR: )
    SEMI: ;
    SEMICOLON: ;
    SINGLE_QUOTE: ''''
    SLASH: /
    SQT: ''''
    STAR: '*'
    TILDE: '~'
    TILDE2: '~'
    UNDER: _
    UNDERSCORE: _

  zmk_combos:
    system_left:
      draw_separate: true
    system_right:
      draw_separate: true
    utils:
      draw_separate: true
    utils_l:
      align: left
    utils_r:
      align: right
    meh_7:
      align: left
    meh_8:
      align: right
    meh_9:
      align: left
    meh_0:
      align: right